### ISSUE TITLE
meson compile o ninja -C ?

### ISSUE THREAD

**Issue by resoli** [M0Rf30/cie-middleware-linux#5]
Salve,
Complimenti per questo lavoro. Volevo solo segnalare che su ubuntu 20.04 attuale il comando `meson` da pacchetto non ha il sottocomando `compile`. Ho usato `ninja` in sua vece. É corretto? 
Il build é terminato correttamente, comunque.

**Comment by eli-schwartz** [comment]
On newer versions of meson, the `meson compile -C builddir/` command is available to run `ninja -C builddir/` on your behalf. It works exactly the same, except for `meson compile` being slower since it has to run a python program first.

The difference between them is that `meson compile` also works on Windows, because it detects if Meson was configured to use Visual Studio solution files instead of ninja. So, `meson compile` may choose to run `msbuild.exe` instead of `ninja.exe`.

**Comment by resoli** [comment]
Many thanks for your explanation!
